PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://example.com#>
PREFIX gufo: <http://purl.org/nemo/gufo#>

# Recupera todos os pacientes que receberam diagnósticos e de quais médicos.
# Esta consulta pode ser facilmente modificada para filtrar pacientes ou médicos.

SELECT DISTINCT
	(STR(?patientName) 	AS ?patient_name)
	(STR(?doctorName) 	AS ?doctor_name)
WHERE {
	?patient rdf:type :Patient;
			 :hasName ?patientName.
	
	?report rdf:type :MedicalReport;
			gufo:mediates ?patient.
	
	?doctor rdf:type :Doctor;
			^gufo:mediates ?report;
			:hasName ?doctorName.
}