PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://example.com#>
PREFIX gufo: <http://purl.org/nemo/gufo#>

# Recupera todos os pacientes fazendo terapia medicamentosa, os
# medicamentos prescritos, as dosagens e os médicos prescritores.

SELECT DISTINCT
	(STR(?patientName)  AS ?patient_name)
	?medicine
	(STR(?dosage)       AS ?medicine_dosage)
	(STR(?doctorName)   AS ?doctor_name)
WHERE {
	?patient rdf:type :Patient;
	         :hasName ?patientName.
	
	?therapy rdf:type :MedicationTherapy;
	         gufo:inheresIn ?patient;
	         gufo:externallyDependsOn ?medicine.

	OPTIONAL { ?medicine :dosage ?dosage. }

	?prescription :prescribes ?therapy;
	              gufo:mediates ?patient;
		          gufo:mediates ?doctor.

	?doctor rdf:type :Doctor;
		    :hasName ?doctorName.
}